# Generated by Django 5.2.17 on 2026-09-27 09:06

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.expressions.RawSQL("uuidv7()", []),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("bill_no", models.TextField()),
                ("document_kind", models.TextField(db_default="bill")),
                ("supplier_id", models.UUIDField()),
                ("purchase_order_id", models.UUIDField(blank=True, null=True)),
                ("journal_entry_id", models.UUIDField(blank=True, null=True)),
                ("bill_date", models.DateField()),
                ("tax_point_date", models.DateField()),
                ("tax_jurisdiction_id", models.UUIDField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(db_default=1, decimal_places=10, max_digits=20),
                ),
                ("status", models.TextField(db_default="draft")),
                ("row_version", models.BigIntegerField(db_default=1)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("credit_of_bill_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("clock_timestamp()", []),
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("clock_timestamp()", []),
                        editable=False,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": '"erp"."purchase_bills"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillAddressSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.expressions.RawSQL("uuidv7()", []),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("purchase_bill_id", models.UUIDField()),
                ("address_kind", models.TextField()),
                ("recipient_name", models.TextField()),
                ("tax_registration_no", models.TextField(blank=True, null=True)),
                ("line_1", models.TextField()),
                ("line_2", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
                ("postal_code", models.TextField(blank=True, null=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": '"erp"."purchase_bill_address_snapshots"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.expressions.RawSQL("uuidv7()", []),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("purchase_bill_id", models.UUIDField()),
                ("line_no", models.IntegerField()),
                ("item_id", models.UUIDField(blank=True, null=True)),
                ("line_account_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit_cost", models.DecimalField(decimal_places=6, max_digits=20)),
                ("net_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("tax_code_id", models.UUIDField(blank=True, null=True)),
                ("credit_of_bill_line_id", models.UUIDField(blank=True, null=True)),
                ("purchase_account_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("inventory_account_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("tax_amount", models.DecimalField(db_default=0, decimal_places=6, max_digits=20)),
                ("gross_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("clock_timestamp()", []),
                        editable=False,
                    ),
                ),
            ],
            options={
                "db_table": '"erp"."purchase_bill_lines"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillTaxComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.expressions.RawSQL("uuidv7()", []),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("purchase_bill_id", models.UUIDField()),
                ("purchase_bill_line_id", models.UUIDField()),
                ("tax_code_id", models.UUIDField()),
                ("tax_code_component_id", models.UUIDField()),
                ("tax_jurisdiction_id", models.UUIDField()),
                ("rate_schedule_id", models.UUIDField()),
                ("tax_rate_version_id", models.UUIDField()),
                ("taxable_base_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("rate_snapshot", models.DecimalField(decimal_places=8, max_digits=12)),
                ("tax_inclusive_snapshot", models.BooleanField()),
                ("tax_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "recoverable_amount",
                    models.DecimalField(db_default=0, decimal_places=6, max_digits=20),
                ),
                ("rate_version_code_snapshot", models.TextField()),
                ("calculation_method_snapshot", models.TextField()),
                ("calculation_base_snapshot", models.TextField()),
                (
                    "fixed_amount_snapshot",
                    models.DecimalField(decimal_places=6, max_digits=20, null=True),
                ),
                ("recovery_percent_snapshot", models.DecimalField(decimal_places=6, max_digits=9)),
                ("rounding_method_snapshot", models.TextField()),
                ("rounding_precision_snapshot", models.SmallIntegerField()),
                ("currency_code_snapshot", models.CharField(max_length=3)),
                ("input_tax_account_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("account_role_snapshot", models.TextField(blank=True, null=True)),
                ("polarity_snapshot", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.expressions.RawSQL("clock_timestamp()", []),
                        editable=False,
                    ),
                ),
            ],
            options={
                "db_table": '"erp"."purchase_bill_tax_components"',
                "managed": False,
            },
        ),
    ]
